faiss_db:
  collection_name: "document_portal"

embedding_model:
  provider: "openai"
  model_name: "text-embedding-3-small"

retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "gemma2-9b-it"
    temperature: 0
    max_tokens: 2048
  openai:
    provider: "openai"
    model_name: "gpt-3.5-turbo"
    temperature: 0
    max_tokens: 2048
